# Generated by Django 4.1 on 2022-09-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='officeCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='offices.offices'),
        ),
    ]
