# Generated by Django 4.1 on 2022-09-12 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orders_customernumber'),
        ('orderd_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderd_info',
            name='orderNumber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
