# Generated by Django 4.1 on 2022-09-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productlines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('productLine', models.CharField(max_length=50)),
                ('textDescription', models.CharField(max_length=4000)),
                ('htmlDescription', models.CharField(max_length=50, null=True)),
                ('image', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
