# Generated by Django 4.1 on 2022-09-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderNumber', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.DateField(null=True)),
                ('requiredDate', models.DateField(null=True)),
                ('shippedDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=15, null=True)),
                ('comments', models.TextField(null=True)),
                ('customerNumber', models.IntegerField(null=True)),
            ],
        ),
    ]
